export const theme = {
  name: "DefaultTheme",
  colors: {
    primary: {
      BLACK: "#151515",
      DARK_GREY: "#666666",
      MIDDLE_GREY: "#b5b5b5",
      LIGHT_GREY: "#f5f5f5",
      WHITE: "#fafafa",
      ERROR: "#e1665d",
    },
    secondary: {
      RED: "#f8c5c3",
      ORANGE: "#f4D5B6",
      GREEN: "#b7d7d3",
      PINK: "#e6bad5",
      PURPLE: "#d2c6e4",
      YELLOW: "#f5e6b3",
      BLUE: "#b6d3e0",
      BROWN: "#d1c8c4",
      GREY: "#dadada",
      MINT: "#B6D8C6",
      LAVENDER: "#D5CBE2",
      PEACH: "#F4D6C6",
      AQUA: "#B4E9E3",
      CORAL: "#FFA5A0",
      LILAC: "#E0CBEF",
      SAGE: "#C9D6CA",
    },
  },
  fonts: {
    Inter_Regular: "Inter_400Regular",
    Inter_Medium: "Inter_500Medium",
    Inter_SemiBold: "Inter_600SemiBold",
    Inter_Bold: "Inter_700Bold",
  },
  sizes: {
    SMALL: 12,
    NORMAL: 14,
    MEDIUM_LARGE: 16,
    LARGE: 20,
    ULTRA_LARGE: 22,
  },
};
